version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - 8085:8085
    volumes:
      - ./wait-for-it:/scripts
    environment:
      SPRING_PROFILE: docker
      CORS_URL: http://localhost:3000
    depends_on:
      - keycloak
    command: bash -c './scripts/wait-for-it.sh keycloak:8080 -t 0 -- sleep 60 && java -jar /app.jar'
  frontend:
    build: ./frontend
    container_name: frontend
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
  keycloak:
    image: jboss/keycloak:11.0.3
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: social_network
      DB_USER: admin
      DB_PASSWORD: admin
    volumes:
      - ./keycloak:/imports
      - ./wait-for-it:/scripts
    depends_on:
      - database
    entrypoint: [ "bash", "./scripts/wait-for-it.sh", "database:5432", "-t", "0", "--", "/opt/jboss/tools/docker-entrypoint.sh", "-b", "0.0.0.0" ]
  database:
    image: library/postgres:13.0-alpine
    container_name: database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social_network
    volumes:
      - ./database/data:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d
      - ./database/generate:/generate