insert into country (id, title)
values  (1, 'Australia'),
        (2, 'Malaysia'),
        (3, 'Korea'),
        (4, 'China'),
        (5, 'Japan'),
        (6, 'India'),
        (7, 'Taiwan'),
        (8, 'Hong Kong'),
        (9, 'Thailand'),
        (11, 'Vietnam'),
        (12, 'France'),
        (13, 'Italy'),
        (14, 'United Arab Emirates'),
        (15, 'Sweden'),
        (16, 'Kazakhstan'),
        (17, 'Portugal'),
        (18, 'Greece'),
        (19, 'Saudi Arabia'),
        (20, 'Russian Federation'),
        (21, 'United Kingdom'),
        (22, 'Denmark'),
        (23, 'United States'),
        (24, 'Canada'),
        (25, 'Mexico'),
        (26, 'Bermuda'),
        (27, 'Puerto Rico'),
        (28, 'Virgin Islands, U.S.'),
        (29, 'Germany'),
        (30, 'Iran'),
        (31, 'Bolivia'),
        (32, 'Montserrat'),
        (33, 'Netherlands'),
        (34, 'Israel'),
        (35, 'Spain'),
        (36, 'Bahamas'),
        (37, 'Saint Vincent and the Grenadines'),
        (38, 'Chile'),
        (39, 'New Caledonia'),
        (40, 'Argentina'),
        (41, 'Dominica'),
        (42, 'Singapore'),
        (43, 'Nepal'),
        (44, 'Philippines'),
        (45, 'Indonesia'),
        (46, 'Pakistan'),
        (47, 'Tokelau'),
        (48, 'New Zealand'),
        (49, 'Cambodia'),
        (50, 'Macau'),
        (51, 'Papua New Guinea'),
        (52, 'Maldives'),
        (53, 'Afghanistan'),
        (54, 'Bangladesh'),
        (55, 'Ireland'),
        (56, 'Belgium'),
        (57, 'Belize'),
        (58, 'Brazil'),
        (59, 'Switzerland'),
        (60, 'South Africa'),
        (61, 'Egypt'),
        (62, 'Nigeria'),
        (63, 'Tanzania'),
        (64, 'Zambia'),
        (65, 'Senegal'),
        (66, 'Ghana'),
        (67, 'Sudan'),
        (68, 'Cameroon'),
        (69, 'Malawi'),
        (70, 'Angola'),
        (71, 'Kenya'),
        (72, 'Gabon'),
        (73, 'Mali'),
        (74, 'Benin'),
        (75, 'Madagascar'),
        (76, 'Chad'),
        (77, 'Botswana'),
        (78, 'Libya'),
        (79, 'Cape Verde'),
        (80, 'Rwanda'),
        (81, 'Mozambique'),
        (82, 'Gambia'),
        (83, 'Lesotho'),
        (84, 'Mauritius'),
        (85, 'Congo'),
        (86, 'Uganda'),
        (87, 'Burkina Faso'),
        (88, 'Sierra Leone'),
        (89, 'Somalia'),
        (90, 'Zimbabwe'),
        (91, 'Democratic Republic Of The Congo'),
        (92, 'Niger'),
        (93, 'Central African Republic'),
        (94, 'Swaziland'),
        (95, 'Togo'),
        (96, 'Guinea'),
        (97, 'Liberia'),
        (98, 'Seychelles'),
        (99, 'Morocco'),
        (100, 'Algeria'),
        (101, 'Mauritania'),
        (102, 'Namibia'),
        (103, 'Djibouti'),
        (105, 'Comoros'),
        (106, 'Reunion'),
        (107, 'Equatorial Guinea'),
        (108, 'Tunisia'),
        (109, 'Turkey'),
        (110, 'Poland'),
        (111, 'Latvia'),
        (112, 'Ukraine'),
        (113, 'Belarus'),
        (114, 'Czech Republic'),
        (115, 'Palestinian Territory'),
        (116, 'Iceland'),
        (117, 'Cyprus'),
        (118, 'Hungary'),
        (119, 'Slovakia'),
        (120, 'Serbia'),
        (121, 'Bulgaria'),
        (122, 'Oman'),
        (123, 'Romania'),
        (124, 'Georgia'),
        (125, 'Norway'),
        (126, 'Armenia'),
        (127, 'Austria'),
        (128, 'Albania'),
        (129, 'Slovenia'),
        (130, 'Panama'),
        (131, 'Brunei Darussalam'),
        (132, 'Sri Lanka'),
        (133, 'Montenegro'),
        (134, 'Europe'),
        (135, 'Tajikistan'),
        (136, 'Iraq'),
        (137, 'Lebanon'),
        (138, 'Moldova'),
        (139, 'Finland'),
        (140, 'Estonia'),
        (141, 'Bosnia and Herzegovina'),
        (142, 'Kuwait'),
        (143, 'Aland Islands'),
        (144, 'Lithuania'),
        (145, 'Luxembourg'),
        (146, 'Antigua and Barbuda'),
        (147, 'Macedonia'),
        (148, 'San Marino'),
        (149, 'Malta'),
        (150, 'Falkland Islands'),
        (151, 'Bahrain'),
        (152, 'Uzbekistan'),
        (153, 'Azerbaijan'),
        (154, 'Monaco'),
        (155, 'Haiti'),
        (156, 'Guam'),
        (157, 'Jamaica'),
        (158, 'United States Minor Outlying Islands'),
        (159, 'Micronesia'),
        (160, 'Ecuador'),
        (161, 'Peru'),
        (162, 'Cayman Islands'),
        (163, 'Colombia'),
        (164, 'Honduras'),
        (165, 'Netherlands Antilles'),
        (166, 'Yemen'),
        (167, 'Virgin Islands, British'),
        (168, 'Syria'),
        (169, 'Nicaragua'),
        (170, 'Dominican Republic'),
        (171, 'Grenada'),
        (172, 'Guatemala'),
        (173, 'Costa Rica'),
        (174, 'El Salvador'),
        (175, 'Venezuela'),
        (176, 'Barbados'),
        (177, 'Trinidad and Tobago'),
        (178, 'Bouvet Island'),
        (179, 'Marshall Islands'),
        (180, 'Cook Islands'),
        (181, 'Gibraltar'),
        (182, 'Paraguay'),
        (247, 'South Sudan'),
        (184, 'Samoa'),
        (185, 'Saint Kitts and Nevis'),
        (186, 'Fiji'),
        (187, 'Uruguay'),
        (188, 'Northern Mariana Islands'),
        (189, 'Palau'),
        (190, 'Qatar'),
        (191, 'Jordan'),
        (192, 'American Samoa'),
        (193, 'Turks and Caicos Islands'),
        (194, 'Saint Lucia'),
        (195, 'Mongolia'),
        (196, 'Holy See'),
        (197, 'Aruba'),
        (198, 'Guyana'),
        (199, 'Suriname'),
        (200, 'Isle of Man'),
        (201, 'Vanuatu'),
        (202, 'Croatia'),
        (203, 'Anguilla'),
        (204, 'Saint Pierre and Miquelon'),
        (205, 'Guadeloupe'),
        (206, 'Saint Martin'),
        (207, 'Guernsey'),
        (208, 'Burundi'),
        (209, 'Turkmenistan'),
        (210, 'Kyrgyzstan'),
        (211, 'Myanmar'),
        (212, 'Bhutan'),
        (213, 'Liechtenstein'),
        (214, 'Faroe Islands'),
        (215, 'Ethiopia'),
        (216, 'Martinique'),
        (217, 'Jersey'),
        (218, 'Andorra'),
        (219, 'Antarctica'),
        (220, 'British Indian Ocean Territory'),
        (221, 'Greenland'),
        (222, 'Guinea-Bissau'),
        (223, 'Eritrea'),
        (224, 'Wallis and Futuna'),
        (225, 'French Polynesia'),
        (226, 'Cuba'),
        (227, 'Tonga'),
        (228, 'Timor-Leste'),
        (229, 'Sao Tome and Principe'),
        (230, 'French Guiana'),
        (231, 'Solomon Islands'),
        (232, 'Tuvalu'),
        (233, 'Kiribati'),
        (234, 'Niue'),
        (235, 'Norfolk Island'),
        (236, 'Nauru'),
        (237, 'Mayotte'),
        (238, 'Pitcairn Islands'),
        (239, 'Cote D`Ivoire'),
        (240, 'Lao'),
        (241, 'Democratic People`s Republic of Korea'),
        (242, 'Svalbard and Jan Mayen'),
        (243, 'Saint Helena'),
        (244, 'Cocos (Keeling) Islands'),
        (245, 'Western Sahara');