version: "3.9"

services:
  backend:
    build: ../backend
    container_name: backend
    ports:
      - 8085:8085
  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - 3000:3000
  keycloak:
    image: jboss/keycloak:11.0.3
    container_name: keycloak
    restart: on-failure
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: POSTGRES
      DB_ADDR: database
      DB_DATABASE: social_network
      DB_USER: admin
      DB_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - database
    volumes:
      - ../keycloak:/imports
  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: social_network
    volumes:
      - ../database/data:/var/lib/postgresql/data
      - ../database/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432