version: "3.9"

services:
  backend:
    build: ../backend
    container_name: backend
    ports:
      - "8080:8080"
  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3000:3000"
  keycloak:
    build: ../keycloak
    container_name: keycloak
    ports:
      - "8085:8080"