server:
  port: 8085

spring:
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/social-network
          jwk-set-uri: http://keycloak:8080/auth/realms/social-network/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
  datasource:
    username: admin
    password: admin

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network

---

spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://database:5432/social_network