server:
  port: ${PORT:8085}
  error:
    include-message: always

spring:
  profiles:
    active: ${SPRING_PROFILE:dev}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/auth/realms/social-network
          jwk-set-uri: http://keycloak:8080/auth/realms/social-network/protocol/openid-connect/certs
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}

cors:
  url: ${CORS_URL:http://localhost:3000}

springdoc:
  swagger-ui:
    path: /docs/ui
  api-docs:
    path: /docs

keycloak:
  admin:
    username: admin
    password: admin
    url: http://keycloak:8080/auth/admin/realms/social-network

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/social_network

---

spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://database:5432/social_network